// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(E_TicaretContext))]
    [Migration("20210501230832_sehend88")]
    partial class sehend88
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Models.Ekrankarti", b =>
                {
                    b.Property<int>("ekrankartıd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ekrankartıd");

                    b.ToTable("Ekrankarti");
                });

            modelBuilder.Entity("Core.Models.TblMudur", b =>
                {
                    b.Property<int>("Müdürıd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Adminıd")
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MüdürMaaş")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Müşıd")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tc")
                        .HasColumnType("int");

                    b.Property<int>("Tel")
                        .HasColumnType("int");

                    b.Property<int?>("Urunıd")
                        .HasColumnType("int");

                    b.Property<int?>("UrunıdNavigationUrunId")
                        .HasColumnType("int");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Müdürıd");

                    b.HasIndex("UrunıdNavigationUrunId");

                    b.ToTable("TblMudurs");
                });

            modelBuilder.Entity("Core.Models.TblMusteri", b =>
                {
                    b.Property<int>("Müşıd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TblMudurNavigationMüdürıd")
                        .HasColumnType("int");

                    b.Property<int>("Tc")
                        .HasColumnType("int");

                    b.Property<int>("Tel")
                        .HasColumnType("int");

                    b.Property<int?>("Urunıd")
                        .HasColumnType("int");

                    b.HasKey("Müşıd");

                    b.HasIndex("TblMudurNavigationMüdürıd");

                    b.ToTable("TblMusteris");
                });

            modelBuilder.Entity("Core.Models.TblPersonel", b =>
                {
                    b.Property<int>("Personelıd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Kategoriıd")
                        .HasColumnType("int");

                    b.Property<int?>("Müdürıd")
                        .HasColumnType("int");

                    b.Property<int?>("MüdürıdNavigationMüdürıd")
                        .HasColumnType("int");

                    b.Property<decimal?>("PersonelMaas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tc")
                        .HasColumnType("int");

                    b.Property<int>("Tel")
                        .HasColumnType("int");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Personelıd");

                    b.HasIndex("MüdürıdNavigationMüdürıd");

                    b.ToTable("TblPersonels");
                });

            modelBuilder.Entity("Core.Models.TblSati", b =>
                {
                    b.Property<int>("KardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cvv")
                        .HasColumnType("int");

                    b.Property<int?>("KartNo")
                        .HasColumnType("int");

                    b.Property<int?>("SonKulanma")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KardId");

                    b.ToTable("TblSatis");
                });

            modelBuilder.Entity("Core.Models.Urunler", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Xiaomiekrankartıd")
                        .HasColumnType("int");

                    b.Property<int?>("ekrankartııd")
                        .HasColumnType("int");

                    b.Property<int?>("mouseId")
                        .HasColumnType("int");

                    b.Property<int?>("ramıd")
                        .HasColumnType("int");

                    b.Property<int?>("ramıd1")
                        .HasColumnType("int");

                    b.Property<int?>("ssdıd")
                        .HasColumnType("int");

                    b.Property<int?>("ssdıd1")
                        .HasColumnType("int");

                    b.HasKey("UrunId");

                    b.HasIndex("Xiaomiekrankartıd");

                    b.HasIndex("mouseId");

                    b.HasIndex("ramıd1");

                    b.HasIndex("ssdıd1");

                    b.ToTable("TblUrunlers");
                });

            modelBuilder.Entity("Core.Models.mouse", b =>
                {
                    b.Property<int>("mouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mouseId");

                    b.ToTable("mouse");
                });

            modelBuilder.Entity("Core.Models.ram", b =>
                {
                    b.Property<int>("ramıd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ramıd");

                    b.ToTable("ram");
                });

            modelBuilder.Entity("Core.Models.ssd", b =>
                {
                    b.Property<int>("ssdıd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ssdıd");

                    b.ToTable("ssd");
                });

            modelBuilder.Entity("Core.Models.TblMudur", b =>
                {
                    b.HasOne("Core.Models.Urunler", "UrunıdNavigation")
                        .WithMany("TblMudurs")
                        .HasForeignKey("UrunıdNavigationUrunId");

                    b.Navigation("UrunıdNavigation");
                });

            modelBuilder.Entity("Core.Models.TblMusteri", b =>
                {
                    b.HasOne("Core.Models.TblMudur", "TblMudurNavigation")
                        .WithMany("Musteris")
                        .HasForeignKey("TblMudurNavigationMüdürıd");

                    b.Navigation("TblMudurNavigation");
                });

            modelBuilder.Entity("Core.Models.TblPersonel", b =>
                {
                    b.HasOne("Core.Models.TblMudur", "MüdürıdNavigation")
                        .WithMany("TblPersonels")
                        .HasForeignKey("MüdürıdNavigationMüdürıd");

                    b.Navigation("MüdürıdNavigation");
                });

            modelBuilder.Entity("Core.Models.Urunler", b =>
                {
                    b.HasOne("Core.Models.Ekrankarti", "Xiaomi")
                        .WithMany("Urunlers")
                        .HasForeignKey("Xiaomiekrankartıd");

                    b.HasOne("Core.Models.mouse", "mouse")
                        .WithMany("Urunlers")
                        .HasForeignKey("mouseId");

                    b.HasOne("Core.Models.ram", "ram")
                        .WithMany("Urunlers")
                        .HasForeignKey("ramıd1");

                    b.HasOne("Core.Models.ssd", "ssd")
                        .WithMany("Urunlers")
                        .HasForeignKey("ssdıd1");

                    b.Navigation("mouse");

                    b.Navigation("ram");

                    b.Navigation("ssd");

                    b.Navigation("Xiaomi");
                });

            modelBuilder.Entity("Core.Models.Ekrankarti", b =>
                {
                    b.Navigation("Urunlers");
                });

            modelBuilder.Entity("Core.Models.TblMudur", b =>
                {
                    b.Navigation("Musteris");

                    b.Navigation("TblPersonels");
                });

            modelBuilder.Entity("Core.Models.Urunler", b =>
                {
                    b.Navigation("TblMudurs");
                });

            modelBuilder.Entity("Core.Models.mouse", b =>
                {
                    b.Navigation("Urunlers");
                });

            modelBuilder.Entity("Core.Models.ram", b =>
                {
                    b.Navigation("Urunlers");
                });

            modelBuilder.Entity("Core.Models.ssd", b =>
                {
                    b.Navigation("Urunlers");
                });
#pragma warning restore 612, 618
        }
    }
}
